### ISSUE TITLE
React & Redux group project: set up your Kanban board

### ISSUE THREAD

**Issue by lily4178993** [Eccb7/space-travellers#49]
In this capstone project, we are team of two: @Eccb7 and @lily4178993.
We have created our [Kanban board](https://github.com/Eccb7/space-travellers/projects/4) that will help us collaborate and finish our [project](https://github.com/Eccb7/space-travellers).

**Comment by prolajumokeoni** [comment]
Hi @lily4178993 and @Eccb7, Kindly update the link in your issue description to the Github project(kanban board)

**Comment by lily4178993** [comment]
Hi @prolajumokeoni. We already updated the link.

**Comment by prolajumokeoni** [comment]
Hi @Team

Your board setup is complete! 
Congratulations! 🎉 
## Highlights
 - Good setup   💯  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lily4178993** [comment]
Thank you @prolajumokeoni for taking the time to review our Kanban board.
Have a geat day!
